//| error_message: "expected start of next field"
field1: "value"
:
